import { PartnerEntity } from '@entities/partners/model/types';

export const mockPartners: PartnerEntity[] = [
  {
    id: '1',
    name: 'Subway',
    address: 'Santa Nella, CA 95322',
    rating: 4.5,
    distance: 1.5,
    freeShipping: true,
    open: true,
    categories: ['Sandwich', 'Salads', 'Fast Food'],
  },
  {
    id: '2',
    name: 'Burger King',
    address: 'Los Banos, CA 93635',
    rating: 4.2,
    distance: 2.1,
    freeShipping: false,
    open: true,
    categories: ['Burgers', 'Fries', 'Drinks'],
  },
  {
    id: '3',
    name: 'Pizza Hut',
    address: 'Merced, CA 95340',
    rating: 3.9,
    distance: 3.5,
    freeShipping: true,
    open: false,
    categories: ['Pizza', 'Pasta', 'Desserts'],
  },
  {
    id: '4',
    name: 'Starbucks',
    address: 'Turlock, CA 95380',
    rating: 4.7,
    distance: 0.8,
    freeShipping: false,
    open: true,
    categories: ['Drinks', 'Breakfast', 'Desserts'],
  },
  {
    id: '5',
    name: 'Taco Bell',
    address: 'Modesto, CA 95354',
    rating: 4.1,
    distance: 4.2,
    freeShipping: true,
    open: false,
    categories: ['Tacos', 'Burritos', 'Fast Food'],
  },
  {
    id: '6',
    name: 'KFC',
    address: 'Fresno, CA 93720',
    rating: 3.8,
    distance: 5.0,
    freeShipping: false,
    open: true,
    categories: ['Fried Chicken', 'BBQ', 'Drinks'],
  },
  {
    id: '7',
    name: 'Panda Express',
    address: 'Madera, CA 93637',
    rating: 4.4,
    distance: 2.7,
    freeShipping: true,
    open: true,
    categories: ['Chinese', 'Rice Bowls', 'Noodles'],
  },
  {
    id: '8',
    name: 'Chipotle',
    address: 'Clovis, CA 93611',
    rating: 4.0,
    distance: 3.0,
    freeShipping: false,
    open: false,
    categories: ['Tacos', 'Rice Bowls', 'Healthy'],
  },
  {
    id: '9',
    name: 'Five Guys',
    address: 'Visalia, CA 93277',
    rating: 4.6,
    distance: 1.9,
    freeShipping: true,
    open: true,
    categories: ['Burgers', 'Fries', 'Drinks'],
  },
  {
    id: '10',
    name: 'In-N-Out Burger',
    address: 'Bakersfield, CA 93312',
    rating: 4.8,
    distance: 0.5,
    freeShipping: true,
    open: true,
    categories: ['Burgers', 'Fries', 'Fast Food'],
  },
  {
    id: '11',
    name: 'Domino’s Pizza',
    address: 'Delano, CA 93215',
    rating: 3.7,
    distance: 4.8,
    freeShipping: false,
    open: false,
    categories: ['Pizza', 'Desserts', 'Drinks'],
  },
  {
    id: '12',
    name: 'Denny’s',
    address: 'Wasco, CA 93280',
    rating: 4.3,
    distance: 2.3,
    freeShipping: true,
    open: true,
    categories: ['Breakfast', 'Pasta', 'Steak'],
  },
  {
    id: '13',
    name: 'Panera Bread',
    address: 'Hanford, CA 93230',
    rating: 4.2,
    distance: 3.6,
    freeShipping: false,
    open: false,
    categories: ['Salads', 'Soup', 'Sandwich'],
  },
  {
    id: '14',
    name: 'Sonic Drive-In',
    address: 'Porterville, CA 93257',
    rating: 3.9,
    distance: 1.2,
    freeShipping: true,
    open: true,
    categories: ['Drinks', 'Burgers', 'Desserts'],
  },
  {
    id: '15',
    name: 'Wendy’s',
    address: 'Reedley, CA 93654',
    rating: 4.0,
    distance: 2.9,
    freeShipping: false,
    open: true,
    categories: ['Burgers', 'Salads', 'Fries'],
  },
];
